// Native harness for wllama's C++ glue (wllama-context.h), driven like the JS worker: single thread, one run_loop per get_result poll, per-request readers.
// See README.md in this directory for why and how to use this.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

// stubs for emscripten-only symbols referenced by wllama-context.h
extern "C" int emscripten_get_callstack(int flags, char *out, size_t maxbytes) {
  (void)flags;
  if (maxbytes > 0) out[0] = '\0';
  return 0;
}
#define EM_LOG_JS_STACK 0
#define EM_LOG_NO_PATHS 0
extern "C" void __real_abort(void) { ::abort(); }

// build-info symbols normally generated by the llama.cpp build
const char *llama_commit() { return "native-test"; }
const char *llama_compiler() { return "native-test"; }
int llama_build_number() { return 0; }
const char *llama_build_target() { return "native-test"; }

#include "ggml.h"
#include "ggml-cpu.h"
extern "C" struct ggml_cplan __real_ggml_graph_plan(
    const struct ggml_cgraph *cgraph, int n_threads, struct ggml_threadpool *tp) {
  return ggml_graph_plan(cgraph, n_threads, tp);
}

#include "wllama-context.h"

// common/log.cpp is excluded from the build (wllama-context.h has its own common_log), stub the rest
#include "log.h"
void common_log_set_file(struct common_log *, const char *) {}
void common_log_set_colors(struct common_log *, log_colors) {}
void common_log_set_prefix(struct common_log *, bool) {}
void common_log_set_timestamps(struct common_log *, bool) {}
void common_log_flush(struct common_log *) {}
void common_log_pause(struct common_log *) {}
void common_log_resume(struct common_log *) {}
void common_log_free(struct common_log *) {}
void common_memory_breakdown_print(const llama_context *) {}
server_response_reader::batch_response server_response_reader::wait_for_all(const std::function<bool()> &) {
  return {};
}

static wllama_context app;

// serialize a glue message and feed it to an action, like the JS side does
template <typename TReq, typename TRes>
static TRes call_action(TReq &req, TRes (wllama_context::*action)(const char *)) {
  glue_outbuf buf;
  req.handler.serialize(buf);
  return (app.*action)(buf.data.data());
}

// glue fields default to "present"; null them all first, then set value + dtype only for the fields the request needs
static void set_all_null(glue_handler &handler) {
  for (auto *f : handler.fields) f->set_null();
}

int main(int argc, char **argv) {
  if (argc < 2) {
    fprintf(stderr, "usage: %s <model.gguf>\n", argv[0]);
    return 1;
  }

  llama_backend_init();

  // ---- load ----
  {
    glue_msg_load_req req;
    set_all_null(req.handler);

    req.model_paths.dtype = GLUE_DTYPE_ARRAY_STRING;
    req.model_paths.arr = {argv[1]};
    req.n_ctx_auto.dtype = GLUE_DTYPE_BOOL;
    req.n_ctx_auto.value = false;
    req.use_mmap.dtype = GLUE_DTYPE_BOOL;
    req.use_mmap.value = true;
    req.use_mlock.dtype = GLUE_DTYPE_BOOL;
    req.use_mlock.value = false;
    req.n_gpu_layers.dtype = GLUE_DTYPE_INT;
    req.n_gpu_layers.value = 0;
    req.n_ctx.dtype = GLUE_DTYPE_INT;
    req.n_ctx.value = 1024;
    req.n_threads.dtype = GLUE_DTYPE_INT;
    req.n_threads.value = 2;
    req.n_batch.dtype = GLUE_DTYPE_INT;
    req.n_batch.value = 1024;
    req.n_parallel.dtype = GLUE_DTYPE_INT;
    req.n_parallel.value = 4;
    req.kv_unified.dtype = GLUE_DTYPE_BOOL;
    req.kv_unified.value = true;
    req.log_level.dtype = GLUE_DTYPE_INT;
    req.log_level.value = 5; // debug

    auto res = call_action(req, &wllama_context::action_load);
    if (!res.success.value) {
      fprintf(stderr, "FAIL: load\n");
      return 1;
    }
    fprintf(stderr, "== model loaded\n");
  }

  auto post_completion = [&](const char *prompt) -> int {
    glue_msg_completion_req req;
    set_all_null(req.handler);
    req.is_chat.dtype = GLUE_DTYPE_BOOL;
    req.is_chat.value = false;
    req.data_json.dtype = GLUE_DTYPE_STRING;
    req.data_json.value = std::string("{\"prompt\":\"") + prompt +
                          "\",\"max_tokens\":10,\"temperature\":0}";
    req.files.dtype = GLUE_DTYPE_ARRAY_RAW;
    auto res = call_action(req, &wllama_context::action_completion);
    if (!res.success.value) {
      fprintf(stderr, "FAIL: completion action\n");
      exit(1);
    }
    fprintf(stderr, "== posted completion req_id=%d prompt=\"%s\"\n",
            res.req_id.value, prompt);
    return res.req_id.value;
  };

  // one JS-style get_result poll; returns has_more
  auto poll = [&](int req_id, std::string &out) -> bool {
    glue_msg_get_result_req req;
    set_all_null(req.handler);
    req.req_id.dtype = GLUE_DTYPE_INT;
    req.req_id.value = req_id;
    auto res = call_action(req, &wllama_context::action_get_result);
    if (res.is_error.value) {
      fprintf(stderr, "FAIL: req %d returned error: %s\n", req_id,
              res.data_json.value.c_str());
      exit(1);
    }
    if (!res.data_json.value.empty() && res.data_json.value != "null") {
      out = res.data_json.value;
    }
    return res.has_more.value;
  };

  // scenario: A is polled a few times alone (mid-generation), then B and C join
  // this forces mixed gen+prompt batches and multi-slot decoding
  int id_a = post_completion("Once upon a time");
  std::string out_a, out_b, out_c;
  bool more_a = true, more_b = true, more_c = true;

  for (int i = 0; i < 4 && more_a; i++) {
    more_a = poll(id_a, out_a);
  }
  fprintf(stderr, "== A polled 4 times, now posting B and C\n");

  int id_b = post_completion("The little girl said");
  int id_c = post_completion("One day, a boy named");

  int guard = 0;
  while ((more_a || more_b || more_c) && guard++ < 500) {
    if (more_a) more_a = poll(id_a, out_a);
    if (more_b) more_b = poll(id_b, out_b);
    if (more_c) more_c = poll(id_c, out_c);
  }

  fprintf(stderr, "== A: %s\n", out_a.substr(0, 200).c_str());
  fprintf(stderr, "== B: %s\n", out_b.substr(0, 200).c_str());
  fprintf(stderr, "== C: %s\n", out_c.substr(0, 200).c_str());

  if (guard >= 500) {
    fprintf(stderr, "FAIL: polling did not converge\n");
    return 1;
  }
  if (out_a.empty() || out_b.empty() || out_c.empty()) {
    fprintf(stderr, "FAIL: missing result\n");
    return 1;
  }
  fprintf(stderr, "== ALL OK\n");
  return 0;
}
