// This file is generated by scripts/generate_wasm_from_cdn.js
// Do not edit this file directly

const WasmFromCDN = {
  'wllama.wasm': 'https://cdn.jsdelivr.net/npm/@wllama/wllama@3.0.0/src/wasm/wllama.wasm',
};

export default WasmFromCDN;